[workspace]
resolver = "3"
members = [
  "helix-core",
  "helix-dap",
  "helix-dap-types",
  "helix-event",
  "helix-loader",
  "helix-lsp",
  "helix-lsp-types",
  "helix-parsec",
  "helix-stdx",
  "helix-term",
  "helix-tui",
  "helix-vcs",
  "helix-view",
  "xtask",
]

default-members = ["helix-term"]

[workspace.package]
version = "26.9.2"
authors = ["Blaž Hrastnik <blaz@mxxn.io>"]
edition = "2024"
rust-version = "1.90"
homepage = "https://helix-editor.com"
repository = "https://github.com/helix-editor/helix"
license = "MPL-2.0"
categories = ["editor"]

[workspace.dependencies]
arc-swap = "1.9"
arrayvec = "0.7"
bitflags = "2.12"
etcetera = "0.11"
foldhash = "0.2"
futures-executor = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["async-await", "std"] }
globset = "0.4"
notify = "8.0.0"
nucleo = "0.5.0"
parking_lot = "0.12"
ropey = { version = "1.6.1", default-features = false, features = ["simd"] }
slotmap = "1.1.1"
sonic-rs = "0.5"
tempfile = "3.27.0"
termina = "0.4"
thiserror = "2.0"
tokio-stream = "0.1.18"
toml = "1.1"
tree-house = { version = "0.4", default-features = false }
unicode-segmentation = "1.13"

# dev dependencies
criterion = { version = "0.8", default-features = false, features = ["cargo_bench_support"] }
quickcheck = { version = "1", default-features = false }

[profile.release]
lto = "thin"

[profile.integration]
inherits = "test"
package.helix-core.opt-level = 2
package.helix-term.opt-level = 2
package.helix-tui.opt-level = 2

[profile.opt]
inherits = "release"
opt-level = 3
strip = true
lto = "fat"
codegen-units = 1
